### ISSUE TITLE
`use-hash-history` is unsupported

### ISSUE THREAD

**Issue by Breefield** [likec4/actions#45]
I'm uploading my built site to AWS S3. Without a hash history paths break if I try and copy/paste them into new tab, etc.
`use-hash-history` is unsupported by this action, but it should in theory resolve my issue.

**Comment by davydkov** [comment]
Hey @Breefield 

Thank you for reporting, fixed in latest release.

Also suggest you to check [likec4#1111](https://github.com/likec4/likec4/issues/1111) if it applies to your case
